import { ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    // Window setup and settings
    title: "audio";

    // -------- Variables --------
    private property <[[string]]> dials: [["Bass", "Vocals", "Treble"], ["Gain", "Reverb", "Crush"]];

    in-out property <[string]> preset_names: [];
    in-out property <[[int]]> preset_values: [];
    out property <bool> new_preset: false;
    out property <bool> delete_preset: false;
    out property <int> deleted_preset: 0;
    out property <bool> rename_preset: false;

    in-out property <[string]> recording_names: [];
    in-out property <[[int]]> recording_values: [];
    out property <int> current_recording: 0;
    out property <int> deleted_recording: 0;
    out property <bool> delete_recording: false;

    out property <[int]> dial_values: [0, 0, 0, 0, 0, 0];

    private property <bool> playing: false;
    in-out property <bool> recording: false;

    private property <length> snap_by: 10px;
    private property <length> next_snap: snap_by;
    private property <length> last_snap: snap_by - snap_by;
    private property <length> dial_pressed: 0px;

    private property <bool> deleting_preset: false;
    private property <bool> renaming_preset: false;
    private property <bool> deleting_recording: false;

    in-out property <string> error_notification: "";
    in-out property <bool> error-recieved: false;

    // -------- Callbacks --------
    callback startup();
    callback update_and_save();
    callback record();

    // -------- Timers --------
    // Loads settings to UI on startup
    Timer {
        interval: 0ms;
        running: true;

        triggered => {
            self.running = false;
            startup();
            dial_values[0] = recording_values[current_recording][0];
            dial_values[1] = recording_values[current_recording][1];
            dial_values[2] = recording_values[current_recording][2];
            dial_values[3] = recording_values[current_recording][3];
            dial_values[4] = recording_values[current_recording][4];
            dial_values[5] = recording_values[current_recording][5];
        }
    }

    // Delays save until animation is finished
    Timer {
        interval: 0.5s;
        running: rename_preset;

        triggered => {
            update_and_save();
            rename_preset = false;
        }
    }

    // Remove error text after period
    Timer {
        interval: 5s;
        running: error-recieved;

        triggered => {
            error_notification = "";
            error-recieved = false;
        }
    }

    // -------- App layout --------
    HorizontalLayout {
        spacing: 32px;
        padding: 12px;

        // Audio dials
        VerticalLayout {
            spacing: 12px;
            
            for group[index] in dials:
            HorizontalLayout {
                spacing: 12px;

                for dial[index2] in group:
                Rectangle {
                    border-width: 1px;
                    border-color: #ffffff;
                    border-radius: 12px;
                    background: #242424;
                    drop-shadow-color: #151515;
                    drop-shadow-blur: 8px;
                    drop-shadow-offset-x: 6px;
                    drop-shadow-offset-y: 6px;
                    
                    VerticalLayout {
                        padding: 12px;
                        spacing: 12px;
                        alignment: center;
    
                        Text {
                            text: dial;
                            font-weight: 700;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                        }

                        HorizontalLayout {
                            alignment: center;

                            TouchArea {
                                mouse-cursor: recording ? default : ew-resize;

                                SwipeGestureHandler {
                                    enabled: !recording;

                                    Rectangle {
                                        border-width: 2px;
                                        border-color: #ffffff;
                                        border-radius: 100px;
                                        background: #242424;
                                        drop-shadow-color: #151515;
                                        drop-shadow-blur: 8px;
                                        drop-shadow-offset-x: 6px;
                                        drop-shadow-offset-y: 6px;
                                        height: 60px;
                                        width: 60px;
            
                                        HorizontalLayout {
                                            padding-top: 12px;
                                            alignment: center;
            
                                            Image {
                                                source: @image-url("icons/dial.svg");
                                                height: 40px;
                                                width: 60px;
                                                rotation-angle: dial_values[index2 + (index * 3)] * 20deg;
                                            }
                                        }
                                    }

                                    moved => {
                                        if dial_pressed != self.pressed-position.x {
                                            next_snap = snap_by;
                                            last_snap = snap_by - snap_by;
                                            dial_pressed = self.pressed-position.x;
                                        }
                                        if self.current-position.x - self.pressed-position.x > next_snap {
                                            if dial_values[index2 + (index * 3)] < 7 {
                                                dial_values[index2 + (index * 3)] += 1;
                                                last_snap = next_snap;
                                                next_snap += snap_by;
                                            }
                                        } else if self.current-position.x - self.pressed-position.x < last_snap {
                                            if dial_values[index2 + (index * 3)] > -7 {
                                                dial_values[index2 + (index * 3)] -= 1;
                                                next_snap = last_snap;
                                                last_snap -= snap_by;
                                            }
                                        }

                                        update_and_save();
                                    }
                                }
                            }
                        }
    
                        Text {
                            text: dial_values[index2 + (index * 3)];
                            vertical-alignment: center;
                            horizontal-alignment: center;
                        }
                    }
                }
            }
        }

        // Presets, recordings, and playback controls
        VerticalLayout {
            spacing: 12px;

            HorizontalLayout {
                spacing: 32px;

                // Presets
                VerticalLayout {
                    spacing: 12px;

                    HorizontalLayout {
                        alignment: start;
                        spacing: 8px;

                        Text {
                            text: "Presets";
                            font-size: 16px;
                            font-weight: 700;
                            vertical-alignment: center;
                        }

                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/plus.svg");
                                width: 20px;
                                height: 20px;
                            }

                            clicked => {
                                new_preset = true;
                                update_and_save();
                                new_preset = false;
                            }
                        }

                        if renaming_preset:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/check.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                renaming_preset = !renaming_preset;
                                rename_preset = true;
                            }
                        }

                        if !renaming_preset:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/rename.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_preset = false;
                                renaming_preset = !renaming_preset;
                            }
                        }

                        if deleting_preset:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/check.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_preset = !deleting_preset;
                            }
                        }

                        if !deleting_preset:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/trash.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                renaming_preset = false;
                                deleting_preset = !deleting_preset;
                            }
                        }
                    }

                    ScrollView {
                        vertical-scrollbar-policy: always-off;
                        
                        VerticalLayout {
                            alignment: start;
                            spacing: renaming_preset ? 8px : 16px;

                            animate spacing {
                                duration: 0.3s;
                                easing: ease-in-out-back;
                            }

                            for preset[index] in preset_values:
                            TouchArea {
                                mouse-cursor: pointer;
                                enabled: !renaming_preset;

                                Rectangle {
                                    border-radius: 8px;
                                    background: deleting_preset ? @linear-gradient(90deg, #dc4242 30%, #ed2e2e00 100%) : renaming_preset ? @linear-gradient(90deg, #3f51b5 30%, #3f51b500 100%) : #ffffff00;

                                    animate background {
                                        duration: 0.2s;
                                    }

                                    VerticalLayout {
                                        padding: deleting_preset || renaming_preset ? 8px: 0px;
                                        spacing: renaming_preset ? 0px : 4px;
                                        alignment: start;

                                        animate padding, spacing {
                                            duration: 0.3s;
                                            easing: ease-in-out-back;
                                        }

                                        if renaming_preset:
                                        TextInput {
                                            text: preset_names[index];
                                            font-weight: 700;

                                            edited => {
                                                preset_names[index] = self.text;
                                            }
                                        }
            
                                        if !renaming_preset:
                                        Text {
                                            text: preset_names[index];
                                            font-weight: 700;
                                            overflow: elide;
                                        }
                
                                        Text {
                                            text: "\{preset[0]}  \{preset[1]}  \{preset[2]}  \{preset[3]}  \{preset[4]}  \{preset[5]}";
                                            overflow: elide;
                                            vertical-alignment: center;
                                            font-size: renaming_preset ? 1px : 12px;
                                            opacity: renaming_preset ? 0% : 100%;

                                            animate font-size, opacity {
                                                duration: 0.3s;
                                                easing: ease-in-out-back;
                                            }
                                        }
                                    }
                                }

                                clicked => {
                                    if deleting_preset {
                                        deleted_preset = index;
                                        delete_preset = true;
                                        update_and_save();
                                        delete_preset = false;
                                    } else {
                                        dial_values[0] = preset[0];
                                        dial_values[1] = preset[1];
                                        dial_values[2] = preset[2];
                                        dial_values[3] = preset[3];
                                        dial_values[4] = preset[4];
                                        dial_values[5] = preset[5];
                                        update_and_save();
                                    }
                                }
                            }
                        }
                    }
                }

                // Recordings
                VerticalLayout {
                    spacing: 12px;

                    HorizontalLayout {
                        alignment: start;
                        spacing: 8px;
                        
                        Text {
                            text: "Recordings";
                            font-size: 16px;
                            font-weight: 700;
                        }

                        if deleting_recording:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/check.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_recording = !deleting_recording;
                            }
                        }

                        if !deleting_recording:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/trash.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_recording = !deleting_recording;
                                playing = false;
                            }
                        }
                    }


                    ScrollView {
                        vertical-scrollbar-policy: always-off;

                        VerticalLayout {
                            alignment: start;
                            spacing: 16px;

                            for recording[index] in recording_values:
                            TouchArea {
                                mouse-cursor: pointer;

                                Rectangle {
                                    border-radius: 8px;
                                    border-width: 1px;
                                    border-color: current_recording == index && !deleting_recording ? @linear-gradient(90deg, #ffffff 10%, #ffffff00 90%) : #ffffff00;
                                    background: deleting_recording ? @linear-gradient(90deg, #dc4242 30%, #ed2e2e00 100%) : #ffffff00;
                                    
                                    animate background, border-color {
                                        duration: 0.2s;
                                    }
                
                                    VerticalLayout {
                                        padding: deleting_recording || current_recording == index ? 8px: 0px;
                                        spacing: 4px;

                                        animate padding {
                                            duration: 0.3s;
                                            easing: ease-in-out-back;
                                        }
            
                                        Text {
                                            text: recording_names[index];
                                            font-weight: 700;
                                            overflow: elide;
                                        }
                
                                        Text {
                                            text: "\{recording[0]}  \{recording[1]}  \{recording[2]}  \{recording[3]}  \{recording[4]}  \{recording[5]}";
                                        }
                                    }
                                }

                                clicked => {
                                    if !deleting_recording {
                                        current_recording = index;
                                        dial_values[0] = recording_values[current_recording][0];
                                        dial_values[1] = recording_values[current_recording][1];
                                        dial_values[2] = recording_values[current_recording][2];
                                        dial_values[3] = recording_values[current_recording][3];
                                        dial_values[4] = recording_values[current_recording][4];
                                        dial_values[5] = recording_values[current_recording][5];
                                    } else {
                                        deleted_recording = index;
                                        delete_recording = true;
                                        update_and_save();
                                        delete_recording = false;
                                        current_recording = 0;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Playback controls
            VerticalLayout {
                spacing: 12px;
                height: 0%;

                // Error notifications
                HorizontalLayout {
                    alignment: center;

                    Text {
                        text: error_notification;
                        color: #dc4242;
                        font-weight: 700;
                    }
                }

                // Control group
                HorizontalLayout {
                    spacing: 12px;

                    back := TouchArea {
                        mouse-cursor: pointer;
                        enabled: !recording && !deleting_recording;

                        Rectangle {
                            border-width: 1px;
                            border-radius: 8px;
                            border-color: #ffffff;
                            background: #242424;
                            drop-shadow-color: #101010;
                            drop-shadow-blur: 8px;
                            drop-shadow-offset-x: 4px;
                            drop-shadow-offset-y: 4px;
                            min-width: 100px;
    
                            HorizontalLayout {
                                padding: 12px;
                                alignment: center;
    
                                Image {
                                    source: @image-url("icons/rewind.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: !back.enabled ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
                            }
                        }
                    }

                    play := TouchArea {
                        mouse-cursor: pointer;
                        enabled: !recording && !deleting_recording;

                        Rectangle {
                            border-width: 1px;
                            border-radius: 8px;
                            border-color: #ffffff;
                            background: #242424;
                            drop-shadow-color: #101010;
                            drop-shadow-blur: 8px;
                            drop-shadow-offset-x: 4px;
                            drop-shadow-offset-y: 4px;
                            min-width: 100px;
    
                            HorizontalLayout {
                                padding: 12px;
                                alignment: center;
    
                                if playing:
                                Image {
                                    source: @image-url("icons/pause.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: !play.enabled ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
        
                                if !playing:
                                Image {
                                    source: @image-url("icons/play.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: !play.enabled ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
                            }
                        }

                        clicked => {
                            playing = !playing;
                        }
                    }

                    next := TouchArea {
                        mouse-cursor: pointer;
                        enabled: !recording && !deleting_recording;

                        Rectangle {
                            border-width: 1px;
                            border-radius: 8px;
                            border-color: #ffffff;
                            background: #242424;
                            drop-shadow-color: #101010;
                            drop-shadow-blur: 8px;
                            drop-shadow-offset-x: 4px;
                            drop-shadow-offset-y: 4px;
                            min-width: 100px;
    
                            HorizontalLayout {
                                padding: 12px;
                                alignment: center;
    
                                Image {
                                    source: @image-url("icons/next.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: !next.enabled ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
                            }
                        }
                    }
                }

                TouchArea {
                    mouse-cursor: pointer;

                    Rectangle {
                        border-width: 1px;
                        border-radius: 8px;
                        border-color: #ffffff;
                        background: #242424;
                        drop-shadow-color: #101010;
                        drop-shadow-blur: 8px;
                        drop-shadow-offset-x: 6px;
                        drop-shadow-offset-y: 6px;
    
                        HorizontalLayout {
                            padding: 12px;
                            alignment: center;

                            if recording:
                            Image {
                                source: @image-url("icons/stop-circle.svg");
                                width: 20px;
                                height: 20px;
                                colorize: #ec4747;
                            }

                            if !recording:
                            Image {
                                source: @image-url("icons/circle.svg");
                                width: 20px;
                                height: 20px;
                                colorize: #ec4747;
                            }
                        }
                    }

                    clicked => {
                        recording = !recording;
                        if recording {
                            playing = false;
                        }
                        record();
                    }
                }
            }
        }
    }
}
