import { ScrollView } from "std-widgets.slint";

struct Preset {
    name: string,
    bass: int,
    vocals: int,
    treble: int,
    gain: int,
    reverb: int,
    crush: int,
}

struct Recording {
    name: string,
    bass: int,
    vocals: int,
    treble: int,
    gain: int,
    reverb: int,
    crush: int,
}

export component AppWindow inherits Window {
    // Window setup and settings
    title: "audio";

    // -------- Menu Bar --------
    MenuBar {

        Menu {
            title: @tr("File");

            MenuItem {
                title: @tr("New preset");
            }

            Menu {
                title: @tr("Delete presets");

                MenuItem {
                    title: @tr("Select presets to delete");
                }

                MenuItem {
                    title: @tr("Delete last preset");
                }

                MenuItem {
                    title: @tr("Delete all presets");
                }
            }

            MenuItem {
                title: @tr("Start recording");
            }

            MenuItem {
                title: @tr("Stop recording");
            }

            Menu {
                title: @tr("Delete Recordings");

                MenuItem {
                    title: @tr("Select recordings to delete");
                }

                MenuItem {
                    title: @tr("Delete last recording");
                }

                MenuItem {
                    title: @tr("Delete all recordings");
                }
            }
        }

        Menu {
            title: @tr("Playback");

            MenuItem {
                title: @tr("Toggle recording playback");
            }

            MenuItem {
                title: @tr("Play previous recording");
            }

            MenuItem {
                title: @tr("Play next recording");
            }
        }
    }

    // -------- Variables --------
    private property <[[string]]> dials: [["Bass", "Vocals", "Treble"], ["Gain", "Reverb", "Crush"]];

    private property <[Preset]> presets: [
    {name: "Preset one", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0},
    {name: "Preset two", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0},
    {name: "Preset three", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0},
    {name: "Preset four", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0}];
    private property <[int]> dial_values: [0, 0, 0, 0, 0, 0];

    private property <[Recording]> recordings: [
    {name: "Recording one", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0},
    {name: "Recording two", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0},
    {name: "Recording three", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0},
    {name: "Recording four", bass: 0, vocals: 0, treble: 0, gain: 0, reverb: 0, crush: 0}];
    
    private property <int> current_preset: 0;
    private property <int> current_recording: 0;
    private property <bool> playing: false;
    private property <bool> recording: false;

    private property <length> snap_by: 10px;
    private property <length> next_snap: snap_by;
    private property <length> last_snap: snap_by - snap_by;
    private property <length> dial_pressed: 0px;

    private property <bool> deleting_preset: false;
    private property <bool> deleting_recording: false;

    // App layout
    HorizontalLayout {
        spacing: 32px;
        padding: 12px;

        // Audio dials
        VerticalLayout {
            spacing: 12px;
            
            for group[index] in dials:
            HorizontalLayout {
                spacing: 12px;

                for dial[index2] in group:
                Rectangle {
                    border-width: 1px;
                    border-color: #ffffff;
                    border-radius: 12px;
                    background: #242424;
                    drop-shadow-color: #151515;
                    drop-shadow-blur: 8px;
                    drop-shadow-offset-x: 6px;
                    drop-shadow-offset-y: 6px;
                    
                    VerticalLayout {
                        padding: 12px;
                        spacing: 12px;
                        alignment: center;
    
                        Text {
                            text: dial;
                            font-weight: 700;
                            vertical-alignment: center;
                            horizontal-alignment: center;
                        }

                        HorizontalLayout {
                            alignment: center;

                            TouchArea {
                                mouse-cursor: ew-resize;

                                SwipeGestureHandler {

                                    Rectangle {
                                        border-width: 2px;
                                        border-color: #ffffff;
                                        border-radius: 100px;
                                        background: #242424;
                                        drop-shadow-color: #151515;
                                        drop-shadow-blur: 8px;
                                        drop-shadow-offset-x: 6px;
                                        drop-shadow-offset-y: 6px;
                                        height: 60px;
                                        width: 60px;
            
                                        HorizontalLayout {
                                            padding-top: 12px;
                                            alignment: center;
            
                                            Image {
                                                source: @image-url("icons/dial.svg");
                                                height: 40px;
                                                width: 60px;
                                                rotation-angle: dial_values[index2 + (index * 3)] * 20deg;
                                            }
                                        }
                                    }

                                    moved => {
                                        if dial_pressed != self.pressed-position.x {
                                            next_snap = snap_by;
                                            last_snap = snap_by - snap_by;
                                            dial_pressed = self.pressed-position.x;
                                        }
                                        if self.current-position.x - self.pressed-position.x > next_snap {
                                            if dial_values[index2 + (index * 3)] < 7 {
                                                dial_values[index2 + (index * 3)] += 1;
                                                last_snap = next_snap;
                                                next_snap += snap_by;
                                            }
                                        } else if self.current-position.x - self.pressed-position.x < last_snap {
                                            if dial_values[index2 + (index * 3)] > -7 {
                                                dial_values[index2 + (index * 3)] -= 1;
                                                next_snap = last_snap;
                                                last_snap -= snap_by;
                                            }
                                        }
                                    }
                                }
                            }
                        }
    
                        Text {
                            text: dial_values[index2 + (index * 3)];
                            vertical-alignment: center;
                            horizontal-alignment: center;
                        }
                    }
                }
            }
        }

        // Presets, recordings, and playback controls
        VerticalLayout {
            spacing: 12px;

            HorizontalLayout {
                spacing: 32px;

                // Presets
                VerticalLayout {
                    spacing: 12px;

                    HorizontalLayout {
                        alignment: start;
                        spacing: 8px;

                        Text {
                            text: "Presets";
                            font-size: 16px;
                            font-weight: 700;
                            vertical-alignment: center;
                        }

                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/plus.svg");
                                width: 20px;
                                height: 20px;
                            }
                        }

                        if deleting_preset:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/check.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_preset = !deleting_preset;
                            }
                        }

                        if !deleting_preset:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/trash.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_preset = !deleting_preset;
                            }
                        }
                    }

                    ScrollView {
                        vertical-scrollbar-policy: always-off;
                        
                        VerticalLayout {
                            alignment: start;
                            spacing: 16px;

                            for preset[index] in presets:
                            TouchArea {
                                mouse-cursor: pointer;

                                Rectangle {
                                    border-radius: 8px;
                                    background: deleting_preset ? @linear-gradient(90deg, #dc4242 30%, #ed2e2e00 100%) : #ffffff00;

                                    animate background {
                                        duration: 0.2s;
                                    }

                                    VerticalLayout {
                                        padding: deleting_preset ? 8px: 0px;
                                        spacing: 4px;
                                        alignment: start;

                                        animate padding {
                                            duration: 0.1s;
                                        }
            
                                        Text {
                                            text: preset.name;
                                            font-weight: 700;
                                            overflow: elide;
                                        }
                
                                        Text {
                                            text: "\{preset.bass} \{preset.vocals} \{preset.treble} \{preset.gain} \{preset.reverb} \{preset.crush}";
                                            overflow: elide;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                // Recordings
                VerticalLayout {
                    spacing: 12px;

                    HorizontalLayout {
                        alignment: start;
                        spacing: 8px;
                        
                        Text {
                            text: "Recordings";
                            font-size: 16px;
                            font-weight: 700;
                        }

                        if deleting_recording:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/check.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_recording = !deleting_recording;
                            }
                        }

                        if !deleting_recording:
                        TouchArea {
                            mouse-cursor: pointer;

                            Image {
                                source: @image-url("icons/trash.svg");
                                width: 16px;
                                height: 16px;
                            }

                            clicked => {
                                deleting_recording = !deleting_recording;
                            }
                        }
                    }


                    ScrollView {
                        vertical-scrollbar-policy: always-off;

                        VerticalLayout {
                            alignment: start;
                            spacing: 16px;

                            for recording[index] in recordings:
                            TouchArea {
                                mouse-cursor: pointer;

                                Rectangle {
                                    border-radius: 8px;
                                    background: deleting_recording ? @linear-gradient(90deg, #dc4242 30%, #ed2e2e00 100%) : #ffffff00;
                                    
                                    animate background {
                                        duration: 0.2s;
                                    }
                
                                    VerticalLayout {
                                        padding: deleting_recording ? 8px: 0px;
                                        spacing: 4px;

                                        animate padding {
                                            duration: 0.1s;
                                        }
            
                                        Text {
                                            text: recording.name;
                                            font-weight: 700;
                                            overflow: elide;
                                        }
                
                                        Text {
                                            text: "\{recording.bass} \{recording.vocals} \{recording.treble} \{recording.gain} \{recording.reverb} \{recording.crush}";
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Playback controls
            VerticalLayout {
                spacing: 12px;
                height: 0%;

                // Control group
                HorizontalLayout {
                    spacing: 12px;

                    TouchArea {
                        mouse-cursor: pointer;
                        enabled: !recording;

                        Rectangle {
                            border-width: 1px;
                            border-radius: 8px;
                            border-color: #ffffff;
                            background: #242424;
                            drop-shadow-color: #101010;
                            drop-shadow-blur: 8px;
                            drop-shadow-offset-x: 4px;
                            drop-shadow-offset-y: 4px;
                            min-width: 100px;
    
                            HorizontalLayout {
                                padding: 12px;
                                alignment: center;
    
                                Image {
                                    source: @image-url("icons/rewind.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: recording ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
                            }
                        }
                    }

                    TouchArea {
                        mouse-cursor: pointer;
                        enabled: !recording;

                        Rectangle {
                            border-width: 1px;
                            border-radius: 8px;
                            border-color: #ffffff;
                            background: #242424;
                            drop-shadow-color: #101010;
                            drop-shadow-blur: 8px;
                            drop-shadow-offset-x: 4px;
                            drop-shadow-offset-y: 4px;
                            min-width: 100px;
    
                            HorizontalLayout {
                                padding: 12px;
                                alignment: center;
    
                                if playing:
                                Image {
                                    source: @image-url("icons/pause.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: recording ? #5d5d5d : #ffffff;
                                }
        
                                if !playing:
                                Image {
                                    source: @image-url("icons/play.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: recording ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
                            }
                        }

                        clicked => {
                            playing = !playing;
                        }
                    }

                    TouchArea {
                        mouse-cursor: pointer;
                        enabled: !recording;

                        Rectangle {
                            border-width: 1px;
                            border-radius: 8px;
                            border-color: #ffffff;
                            background: #242424;
                            drop-shadow-color: #101010;
                            drop-shadow-blur: 8px;
                            drop-shadow-offset-x: 4px;
                            drop-shadow-offset-y: 4px;
                            min-width: 100px;
    
                            HorizontalLayout {
                                padding: 12px;
                                alignment: center;
    
                                Image {
                                    source: @image-url("icons/next.svg");
                                    width: 20px;
                                    height: 20px;
                                    colorize: recording ? #5d5d5d : #ffffff;

                                    animate colorize {
                                        duration: 0.1s;
                                    }
                                }
                            }
                        }
                    }
                }

                TouchArea {
                    mouse-cursor: pointer;

                    Rectangle {
                        border-width: 1px;
                        border-radius: 8px;
                        border-color: #ffffff;
                        background: #242424;
                        drop-shadow-color: #101010;
                        drop-shadow-blur: 8px;
                        drop-shadow-offset-x: 6px;
                        drop-shadow-offset-y: 6px;
    
                        HorizontalLayout {
                            padding: 12px;
                            alignment: center;

                            if recording:
                            Image {
                                source: @image-url("icons/stop-circle.svg");
                                width: 20px;
                                height: 20px;
                                colorize: #ec4747;
                            }

                            if !recording:
                            Image {
                                source: @image-url("icons/circle.svg");
                                width: 20px;
                                height: 20px;
                                colorize: #ec4747;
                            }
                        }
                    }

                    clicked => {
                        recording = !recording;
                        if recording {
                            playing = false;
                        }
                    }
                }
            }
        }
    }
}
